name: Auto PR from feature branches

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cria (ou atualiza) um PR da feature/* para develop
      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Merge ${{ github.ref_name }} into develop'
          body: |
            PR criado automaticamente para revisão e merge manual.
            
            Por favor, revise e faça o merge deste PR manualmente.
          # Não inserir merge-method! Isso impede merge automático.
          # Não use draft: true, pois PRs já estarão abertos para revisão