name: Continuous integration

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cria (ou atualiza) um PR da feature/* para develop,
      # sem mergear automaticamente
      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v7
        with:
          type: now
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
