name: Continuous integration

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'feature/*'
    # Removido o 'pull_request' para deixar mais claro

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v7
        with:
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Merge ${{ github.ref_name }} into develop'
          body: |
            Pull request automático para merge da feature na develop.
            > Atenção: O merge NÃO será feito automaticamente. Por favor, revise e faça o merge manualmente.
          token: ${{ secrets.GITHUB_TOKEN }}